### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by mssct-1999** [maxkueng/node-musicbrainz#27]
Hi,

I'm using your module for VueJS development. Do you have a documentation/description of each functions of your module ?

Thanks in advance !

**Comment by maxkueng** [comment]
Unfortunately, what's in the README is all I have. This library is very old and I haven't used it in a while. I originally wrote it for tagging CDs where everything would always start with a `DiscId` and all further lookups would continue from there. And the plan was to rewrite it once the JSON API comes out of beta, which it hasn't in 8 years or so. The library currently uses the XML API.

I don't have plans to add comprehensive documentation any time soon.

The [source code](https://github.com/maxkueng/node-musicbrainz/blob/f0a1fe44f31f823dbc4b85c321c2aba1f0d67ffa/lib/musicbrainz.js#L611-L781) isn't actually too bad to read as a documentation. You can see which types of entities have which properties and such. Other than that, all the names and terminology follow the [MusicBrainz XML API V2 documentation](https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2).

You can also use the `mb.lookup(resourceType, mbid, includes, force, callback)` ([source](https://github.com/maxkueng/node-musicbrainz/blob/f0a1fe44f31f823dbc4b85c321c2aba1f0d67ffa/lib/musicbrainz.js#L798-L852)) function which maps directly to the [/lookup route](https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2#Lookups) in the XML API.
